jobs:
- name: master
  templates:
  - name: docker
  - name: etcd
  - name: flannel
  - name: kubernetes-minion
  - name: kubernetes-master
  instances: 1
  resource_pool: default
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( merge ))
  properties:
    networks:
      apps: default
- name: minion
  templates:
  - name: docker
  - name: etcd
  - name: flannel
  - name: kubernetes-minion
  instances: 2
  resource_pool: default
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( merge ))
  properties:
    networks:
      apps: default
- name: create-kubernetes-dns
  lifecycle: errand
  templates:
  - name: create-kubernetes-dns
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default
- name: guestbook-example
  lifecycle: errand
  templates:
  - name: guestbook-example
  - name: flannel
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default

properties:
  apiserver:
    host: (( static_ips(0) ))
    machines: (( merge ))
    basic-auth: (( merge || [] ))
    token-auth: (( merge || [] ))
  etcd:
    machines: (( merge ))
    require_ssl: false
    peer_require_ssl: false
  cloud-provider: (( merge || ~ ))
  cloud-credentials:
    master: (( merge || {} ))
    minion: (( merge || {} ))

resource_pools: (( merge ))
