meta:
  aws:
    az: (( merge ))

networks: (( merge ))

compilation:
  cloud_properties:
    availability_zone: (( meta.aws.az ))
    instance_type: m3.large

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    <<: (( merge ))
    instance_type: m3.large
    availability_zone: (( meta.aws.az ))

- name: master
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    <<: (( merge ))
    instance_type: m3.large
    availability_zone: (( meta.aws.az ))

jobs:
- name: master
  instances: 3
  networks:
  - name: default
    static_ips: (( static_ips(0, 1, 2) ))
- name: minion
  instances: 2
  networks:
  - name: default
    static_ips: (( static_ips(3, 4) ))
- name: guestbook-example
  lifecycle: errand
  instances: 1
  networks:
  - name: default

properties:
  <<: (( merge ))
  apiserver:
    <<: (( merge ))
    host: (( jobs.master.networks.default.static_ips.[0] ))
    hosts: (( jobs.master.networks.default.static_ips ))
  consul:
    <<: (( merge ))
    join_host: (( jobs.master.networks.default.static_ips.[0] ))
  etcd:
    machines: (( jobs.master.networks.default.static_ips jobs.minion.networks.default.static_ips ))
