meta:
  aws:
    az: ~

networks: (( merge ))

compilation:
  cloud_properties:
    availability_zone: (( meta.aws.az ))
    instance_type: m3.large

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.large
    availability_zone: (( meta.aws.az ))

jobs:
- name: master
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
- name: minion
  instances: 2
  networks:
  - name: default
    static_ips: (( static_ips(1, 2) ))
- name: guestbook-example
  lifecycle: errand
  instances: 1
  networks:
  - name: default

properties:
  apiserver:
    host: (( jobs.master.networks.default.static_ips.[0] ))
    machines: (( jobs.master.networks.default.static_ips jobs.minion.networks.default.static_ips ))
  etcd:
    machines: (( jobs.master.networks.default.static_ips jobs.minion.networks.default.static_ips ))
