director_uuid: DIRECTOR_UUID

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: consul
  properties:
    consul:
      default_recursor: 8.8.8.8
      ssl_ca: -- SECRET --
      ssl_cert:  -- SECRET --
      ssl_key:  -- SECRET --
      domain: kubernetes
      encrypt: SECRETKEY
  networks:
  - name: services
    static_ips:
    - (( grab terraform_outputs.kubernetes_static_ips.[0] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[1] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[2] ))
- name: etcd
  vm_extension: kubernetes-etcd-profile
  networks:
  - name: services
    static_ips:
    - (( grab terraform_outputs.kubernetes_static_ips.[3] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[4] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[5] ))
- name: master
  vm_extension: kubernetes-master-profile
  networks:
  - name: services
    static_ips:
    - (( grab terraform_outputs.kubernetes_static_ips.[6] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[7] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[8] ))
- name: minion
  vm_extension: kubernetes-minion-profile
  networks:
  - name: services
    static_ips:
    - (( grab terraform_outputs.kubernetes_static_ips.[9] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[10] ))
    - (( grab terraform_outputs.kubernetes_static_ips.[11] ))