meta:
  aws:
    az: (( param "please define availability zone" ))

compilation:
  cloud_properties:
    availability_zone: (( grab meta.aws.az ))
    instance_type: m3.large

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.large
    availability_zone: (( grab meta.aws.az ))

- name: master
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.large
    availability_zone: (( grab meta.aws.az ))

jobs:
- name: consul
  instances: 3
  networks:
  - name: default
    static_ips: (( static_ips(5, 6, 7) ))

- name: master
  instances: 3
  networks:
  - name: default
    static_ips: (( static_ips(0, 1, 2) ))

- name: minion
  instances: 2
  networks:
  - name: default
    static_ips: (( static_ips(3, 4) ))

- name: guestbook-example
  lifecycle: errand
  instances: 1
  networks:
  - name: default

properties:
  nodes: (( grab jobs.master.networks.default.static_ips jobs.minion.networks.default.static_ips ))
  apiserver:
    host: (( grab jobs.master.networks.default.static_ips.[0] ))
    hosts: (( grab jobs.master.networks.default.static_ips ))
  consul:
    join_host: (( grab jobs.consul.networks.default.static_ips.[0] ))
    join_hosts: (( grab jobs.consul.networks.default.static_ips ))
  etcd:
    machines: (( grab jobs.master.networks.default.static_ips jobs.minion.networks.default.static_ips ))
