jobs:
- name: consul
  templates:
  - {name: consul, release: consul}
  instances: 3
  resource_pool: default
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( merge ))

- name: master
  <<: (( merge ))
  templates:
  - {name: docker, release: kubernetes}
  - {name: etcd, release: kubernetes}
  - {name: flannel, release: kubernetes}
  - {name: kubernetes-minion, release: kubernetes}
  - {name: kubernetes-master, release: kubernetes}
  instances: 3
  resource_pool: master
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( merge ))
  properties:
    networks:
      apps: default
    manifest-dirs: [/var/vcap/jobs/kubernetes-master/manifests]

- name: minion
  <<: (( merge ))
  templates:
  - {name: docker, release: kubernetes}
  - {name: etcd, release: kubernetes}
  - {name: flannel, release: kubernetes}
  - {name: kubernetes-minion, release: kubernetes}
  instances: 3
  resource_pool: default
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( merge ))
  properties:
    networks:
      apps: default

- name: create-kubernetes-dns
  lifecycle: errand
  templates:
  - {name: create-kubernetes-dns, release: kubernetes}
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default
- name: guestbook-example
  lifecycle: errand
  templates:
  - {name: guestbook-example, release: kubernetes}
  - {name: flannel, release: kubernetes}
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default

properties:
  <<: (( merge ))
  apiserver: (( merge ))
  consul:
    <<: (( merge ))
    default_recursor: (( merge ))
    ssl_ca: (( merge ))
    ssl_cert: (( merge ))
    ssl_key: (( merge ))
    domain: kubernetes
    encrypt: (( merge ))
  etcd:
    machines: (( merge ))
    require_ssl: false
    peer_require_ssl: false
  certs: (( merge ))
  cloud-provider: (( merge || ~ ))
  cloud-credentials: (( merge || {} ))

resource_pools: (( merge ))
