---
name: kubernetes

director_uuid: (( param "please define director uuid" ))

releases:
- name: kubernetes
  version: latest
- name: consul
  version: latest
- name: os-conf
  url: "https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=22.0.0"
  sha1: "6946056ad69ae378cb89c9ef76daf66370a7dc6a" 

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1
  serial: true
