jobs:
- name: consul
  templates:
  - {name: consul, release: consul}
  instances: 3
  resource_pool: default
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( param "please define static ips" ))

- name: master
  templates:
  - {name: docker, release: kubernetes}
  - {name: etcd, release: kubernetes}
  - {name: flannel, release: kubernetes}
  - {name: kubernetes-minion, release: kubernetes}
  - {name: kubernetes-master, release: kubernetes}
  instances: 3
  resource_pool: master
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( param "please define static ips" ))
  properties:
    networks:
      apps: default
    manifest-dirs: [/var/vcap/jobs/kubernetes-master/manifests]

- name: minion
  templates:
  - {name: docker, release: kubernetes}
  - {name: etcd, release: kubernetes}
  - {name: flannel, release: kubernetes}
  - {name: kubernetes-minion, release: kubernetes}
  instances: 3
  resource_pool: default
  persistent_disk: 65536
  networks:
  - name: default
    static_ips: (( param "please define static ips" ))
  properties:
    networks:
      apps: default

- name: create-kubernetes-dns
  lifecycle: errand
  templates:
  - {name: create-kubernetes-dns, release: kubernetes}
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default

- name: create-kubernetes-monitoring
  lifecycle: errand
  templates:
  - {name: create-kubernetes-monitoring, release: kubernetes}
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default

- name: guestbook-example
  lifecycle: errand
  templates:
  - {name: guestbook-example, release: kubernetes}
  - {name: flannel, release: kubernetes}
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    networks:
      apps: default

properties:
  apiserver:
    hosts: (( param "please define apiserver hosts" ))
  etcd:
    machines: (( param "please define etcd machines" ))
    require_ssl: false
    peer_require_ssl: false
  certs: {}
  cloud-provider: ~
  cloud-credentials: {}
